/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package student.simulator;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Sledgehammer
 */
public class Party extends javax.swing.JFrame {

    /**
     * Creates new form VideoGame
     */
    public Party() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/finnispartying.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        double randNumber = Math.random();
        double randomNumber = randNumber * 100;
        int randomInt = (int)randomNumber + 1;
        int changer = 0;
        int gradeschanger = 0;
        if((randomInt>20)&&(randomInt<80)){
            final ImageIcon icon = new ImageIcon("src/resources/partay.png");
            Image image2 = icon.getImage().getScaledInstance(130,100,0);
            JOptionPane.showMessageDialog(null, """
                                            You danced to Skrillex and ingested legal substances.\n
                                                That's what people do at parties, right?\n
                                                Happiness increased by 15.""", "Partay Results", JOptionPane.PLAIN_MESSAGE, new ImageIcon(image2));
            changer = 15;
            gradeschanger = -9;
        }
        if((randomInt<=20)){
            final ImageIcon icon = new ImageIcon("src/resources/rippartay.png");
            Image image2 = icon.getImage().getScaledInstance(130,100,0);
            JOptionPane.showMessageDialog(null, """
                                            You woke up late for class.\n
                                                I mean, REALLY late for class. You kind of slept through the entire day.\n
                                                You can't remember the events of last night, but social media paints you an embarrassing impression.\n
                                                Did I mention that you missed the exam?\n
                                                Happiness decreased by 35, and... your grades take a toll.""", "Partay Results", JOptionPane.PLAIN_MESSAGE, new ImageIcon(image2));
            changer = -35;
            gradeschanger = -25;
        }
        if((randomInt>=80)){
            final ImageIcon icon = new ImageIcon("src/resources/awesomepartay.png");
            Image image2 = icon.getImage().getScaledInstance(130,100,0);
            JOptionPane.showMessageDialog(null, """
                                            What's crack-a-lackin', life of the party?\n
                                                Hey remember when you... and you... then... you did the...\n
                                                and you could do ANYTHING?!?!?\n
                                                Wow, that was awesome. Happiness increased by 25.""", "Partay Results", JOptionPane.PLAIN_MESSAGE, new ImageIcon(image2));
            changer = 25;
            gradeschanger = -5;
        }
        levels instance = levels.getInstance();
        instance.setHappiness(changer);
        instance.setGrades(gradeschanger);
        dispose();
    }//GEN-LAST:event_formWindowOpened

    /**
     * 
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Party.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Party.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Party.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Party.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Party().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
