
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hello;
    import javax.swing.ImageIcon;
    import javax.swing.Icon;
    import java.awt.BorderLayout;
    import java.awt.EventQueue;
    import java.awt.event.ActionEvent;
    import java.awt.event.ActionListener;
    import java.awt.image.BufferedImage;
    import java.io.File;
    import java.io.IOException;
    import java.util.ArrayList;
    import java.util.List;
    import javax.imageio.ImageIO;
    import javax.swing.ImageIcon;
    import javax.swing.JButton;
    import javax.swing.JFrame;
    import javax.swing.JLabel;
    import javax.swing.UIManager;
    import javax.swing.UnsupportedLookAndFeelException;
    import java.nio.file.*;
    import java.io.File;
    import java.io.IOException;
    import javax.imageio.ImageIO;
    import java.io.File;
    import java.io.FileInputStream;
    import java.io.IOException;
    import java.io.InputStream;
    import javazoom.jl.player.Player;

    
/**
 *
 * @author jacques fleischer
 */
public class CharacterSelect extends javax.swing.JFrame {

    
    
    /**
     * Creates new form NewJFrame
     */
    public CharacterSelect() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        currentchar = new javax.swing.JLabel();
        rightbutton = new javax.swing.JButton();
        leftbutton = new javax.swing.JButton();
        okbutton = new javax.swing.JButton();
        gobackbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MDCstudentSIMULATOR");
        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));
        setSize(new java.awt.Dimension(600, 400));

        jLabel1.setFont(new java.awt.Font("Bachelor Pad College JL", 0, 40)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Choose YourCharacter");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        currentchar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bluedude.png"))); // NOI18N

        rightbutton.setBackground(new java.awt.Color(242, 242, 242));
        rightbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow-01.png"))); // NOI18N
        rightbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rightbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightbuttonActionPerformed(evt);
            }
        });

        leftbutton.setBackground(new java.awt.Color(242, 242, 242));
        leftbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow-flip.png"))); // NOI18N
        leftbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        leftbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftbuttonActionPerformed(evt);
            }
        });

        okbutton.setBackground(new java.awt.Color(153, 255, 153));
        okbutton.setFont(new java.awt.Font("TF2 Build", 0, 30)); // NOI18N
        okbutton.setText("OK");
        okbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        okbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        okbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okbuttonActionPerformed(evt);
            }
        });

        gobackbutton.setBackground(new java.awt.Color(255, 204, 204));
        gobackbutton.setFont(new java.awt.Font("TF2 Build", 0, 30)); // NOI18N
        gobackbutton.setText("GO BACK");
        gobackbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gobackbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gobackbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gobackbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(leftbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(gobackbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(currentchar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rightbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(currentchar, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(leftbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rightbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(102, 102, 102)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(okbutton)
                                .addGap(16, 16, 16))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(gobackbutton)
                                .addGap(15, 15, 15))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private List<BufferedImage> images;
    int setter = 0;
    int[] setterArray = new int[]{1,2,3};
    WhichCharacter picked = new WhichCharacter();
    
    private void rightbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightbuttonActionPerformed
        // TODO add your handling code here:
        
        String pink = "src/main/java/resources/pinkdude.png";
        String blue = "src/main/java/resources/bluedude.png";
        String yellow = "src/main/java/resources/yellowdude.png";
        try {
        if (setter == 0){
            currentchar.setIcon(new ImageIcon(ImageIO.read(new File(pink))));
            setter++;
            return;
        } if (setter == 1) {
            currentchar.setIcon(new ImageIcon(ImageIO.read(new File(yellow))));
            setter++;
            return;
        } if (setter == 2) {
            currentchar.setIcon(new ImageIcon(ImageIO.read(new File(blue))));
            setter = 0;
        }
        
        } catch (IOException exp) {
            exp.printStackTrace();
        }
        
        
    }//GEN-LAST:event_rightbuttonActionPerformed

    private void leftbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftbuttonActionPerformed
        // TODO add your handling code here:
        String pink = "src/main/java/resources/pinkdude.png";
        String blue = "src/main/java/resources/bluedude.png";
        String yellow = "src/main/java/resources/yellowdude.png";
        try {
        // String cwd = Path.of("").toAbsolutePath().toString();
        // System.out.println(cwd);
        if (setter == 0){
            currentchar.setIcon(new ImageIcon(ImageIO.read(new File(yellow))));
            setter = 2;
            return;
        } if (setter == 1) {
            currentchar.setIcon(new ImageIcon(ImageIO.read(new File(blue))));
            setter = 0;
            return;
        } if (setter == 2) {
            currentchar.setIcon(new ImageIcon(ImageIO.read(new File(pink))));
            setter=1;
        }
        
        } catch (IOException exp) {
            exp.printStackTrace();
        }
    }//GEN-LAST:event_leftbuttonActionPerformed

    private void okbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okbuttonActionPerformed
        // TODO add your handling code here:
        WhichCharacter instancechar = WhichCharacter.getInstance();
        instancechar.Play(setter);
        PausablePlayer.main("PlayLicorice");
        
        dispose();
        new GameStart().setVisible(true);
        playermusic z = playermusic.getInstance();
        z.Stop();
        z.Play("src/main/java/resources/licorice.mp3");
    }//GEN-LAST:event_okbuttonActionPerformed

    private void gobackbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gobackbuttonActionPerformed
        // TODO add your handling code here:
        playermusic x = playermusic.getInstance();
        
        x.Stop();
        dispose();
        new MainWindow().setVisible(true);
    }//GEN-LAST:event_gobackbuttonActionPerformed

        
    

    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CharacterSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CharacterSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CharacterSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CharacterSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
       
        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CharacterSelect().setVisible(true);
            }
        });
        
        
            
        }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel currentchar;
    private javax.swing.JButton gobackbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton leftbutton;
    private javax.swing.JButton okbutton;
    private javax.swing.JButton rightbutton;
    // End of variables declaration//GEN-END:variables
}
