
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hello;

import javax.swing.ImageIcon;
import javax.swing.Icon;
import java.awt.BorderLayout;
import java.awt.EventQueue;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import java.nio.file.*;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import javazoom.jl.player.Player;

/**
 *
 * @author jacques fleischer
 */
public class CharacterSelect extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public CharacterSelect() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        currentchar = new javax.swing.JLabel();
        rightbutton = new javax.swing.JButton();
        leftbutton = new javax.swing.JButton();
        okbutton = new javax.swing.JButton();
        gobackbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MDCstudentSIMULATOR");
        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));
        setSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Bachelor Pad College JL", 0, 40)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Choose YourCharacter");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 10, 543, 49);

        currentchar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bluedude.png"))); // NOI18N
        getContentPane().add(currentchar);
        currentchar.setBounds(160, 60, 257, 325);

        rightbutton.setBackground(new java.awt.Color(242, 242, 242));
        rightbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow-01.png"))); // NOI18N
        rightbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rightbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(rightbutton);
        rightbutton.setBounds(460, 150, 110, 78);

        leftbutton.setBackground(new java.awt.Color(242, 242, 242));
        leftbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow-flip.png"))); // NOI18N
        leftbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        leftbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(leftbutton);
        leftbutton.setBounds(30, 150, 121, 77);

        okbutton.setBackground(new java.awt.Color(153, 255, 153));
        okbutton.setFont(new java.awt.Font("TF2 Build", 0, 30)); // NOI18N
        okbutton.setText("OK");
        okbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        okbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        okbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(okbutton);
        okbutton.setBounds(470, 310, 111, 37);

        gobackbutton.setBackground(new java.awt.Color(255, 204, 204));
        gobackbutton.setFont(new java.awt.Font("TF2 Build", 0, 30)); // NOI18N
        gobackbutton.setText("GO BACK");
        gobackbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gobackbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gobackbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gobackbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(gobackbutton);
        gobackbutton.setBounds(20, 310, 170, 37);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private List<BufferedImage> images;
    int setter = 0;
    int[] setterArray = new int[] { 1, 2, 3 };
    WhichCharacter picked = new WhichCharacter();

    private void rightbuttonActionPerformed(java.awt.event.ActionEvent evt) {
        // Paths to images as resources inside the JAR
        String pink = "/pinkdude.png";
        String blue = "/bluedude.png";
        String yellow = "/yellowdude.png";

        try {
            if (setter == 0) {
                // Load pinkdude.png from the classpath
                currentchar.setIcon(new ImageIcon(ImageIO.read(getClass().getResourceAsStream(pink))));
                setter++;
                return;
            }
            if (setter == 1) {
                // Load yellowdude.png from the classpath
                currentchar.setIcon(new ImageIcon(ImageIO.read(getClass().getResourceAsStream(yellow))));
                setter++;
                return;
            }
            if (setter == 2) {
                // Load bluedude.png from the classpath
                currentchar.setIcon(new ImageIcon(ImageIO.read(getClass().getResourceAsStream(blue))));
                setter = 0;
            }
        } catch (IOException exp) {
            exp.printStackTrace();
        }
    }

    // GEN-LAST:event_rightbuttonActionPerformed

    private void leftbuttonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_leftbuttonActionPerformed
        // TODO add your handling code here:
        String pink = "/pinkdude.png";
        String blue = "/bluedude.png";
        String yellow = "/yellowdude.png";
        try {
            // String cwd = Path.of("").toAbsolutePath().toString();
            // System.out.println(cwd);
            if (setter == 0) {
                currentchar.setIcon(new ImageIcon(ImageIO.read(getClass().getResourceAsStream(yellow))));
                setter = 2;
                return;
            }
            if (setter == 1) {
                currentchar.setIcon(new ImageIcon(ImageIO.read(getClass().getResourceAsStream(blue))));
                setter = 0;
                return;
            }
            if (setter == 2) {
                currentchar.setIcon(new ImageIcon(ImageIO.read(getClass().getResourceAsStream(pink))));
                setter = 1;
            }

        } catch (IOException exp) {
            exp.printStackTrace();
        }
    }// GEN-LAST:event_leftbuttonActionPerformed

    private void okbuttonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        WhichCharacter instancechar = WhichCharacter.getInstance();
        instancechar.Play(setter);
        // PausablePlayer.main("PlayLicorice");

        dispose();
        new GameStart().setVisible(true);

        // Get the singleton instance of the playermusic class
        playermusic z = playermusic.getInstance();

        // Check if licorice.mp3 is already playing
        if (!z.getPlayingNow().equals("/licorice.mp3")) {
            z.Stop(); // Stop any currently playing music
            z.Play("/licorice.mp3"); // Play licorice.mp3 only if it's not already playing
        }
    }

    // GEN-LAST:event_okbuttonActionPerformed

    private void gobackbuttonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_gobackbuttonActionPerformed
        // TODO add your handling code here:
        playermusic x = playermusic.getInstance();

        x.Stop();
        dispose();
        new MainWindow().setVisible(true);
    }// GEN-LAST:event_gobackbuttonActionPerformed

    public static void main() {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CharacterSelect.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CharacterSelect.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CharacterSelect.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CharacterSelect.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CharacterSelect().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel currentchar;
    private javax.swing.JButton gobackbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton leftbutton;
    private javax.swing.JButton okbutton;
    private javax.swing.JButton rightbutton;
    // End of variables declaration//GEN-END:variables
}
