/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hello;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Sledgehammer
 */
public class Lecture extends javax.swing.JFrame {

    /**
     * Creates new form VideoGame
     */
    public Lecture() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/attendingclass.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        double randNumber = Math.random();
        double randomNumber = randNumber * 100;
        int randomInt = (int)randomNumber + 1;
        int changer = 0;
        int gradeschanger = 0;
        if((randomInt>5)&&(randomInt<95)){
            final ImageIcon icon = new ImageIcon("src/main/java/resources/lecture.png");
            Image image2 = icon.getImage().getScaledInstance(130,100,0);
            JOptionPane.showMessageDialog(null, "You attended your online programming class and paid attention.\nGrades increased a bit.", "Lecture Results", JOptionPane.PLAIN_MESSAGE, new ImageIcon(image2));
            changer = -10;
            gradeschanger = 4;
        }
        if((randomInt<=5)){
            final ImageIcon icon = new ImageIcon("src/main/java/resources/riplecture.png");
            Image image2 = icon.getImage().getScaledInstance(130,100,0);
            JOptionPane.showMessageDialog(null, "You ended up getting sick with some stomach bug and could not\nconcentrate on what the professor was saying. Too bad!\nGrades and happiness go down a bit.", "Lecture Results", JOptionPane.PLAIN_MESSAGE, new ImageIcon(image2));
            changer = -20;
            gradeschanger = -10;
        }
        if((randomInt>=95)&&(randomInt<99)){
            final ImageIcon icon = new ImageIcon("src/main/java/resources/awesomelecture.png");
            Image image2 = icon.getImage().getScaledInstance(130,100,0);
            JOptionPane.showMessageDialog(null, "You absolutely stole the show. The professor asked a difficult question\nand you hit the nail on the head. Everyone thinks you're some wizard but\nyou just got it from stackoverflow.\nDoesn't matter, looked cool.", "Lecture Results", JOptionPane.PLAIN_MESSAGE, new ImageIcon(image2));
            changer = 5;
            gradeschanger = 8;
        }
        if((randomInt>=99)){
            final ImageIcon icon = new ImageIcon("src/main/java/resources/awesomelecture.png");
            Image image2 = icon.getImage().getScaledInstance(130,100,0);
            JOptionPane.showMessageDialog(null, "There was this person in the Zoom who private messaged you, complementing\nyour profile picture. You met up with this classmate and fell madly in love.\nYou couldn't be any happier.", "Lecture Results", JOptionPane.PLAIN_MESSAGE, new ImageIcon(image2));
            changer = 100;
            gradeschanger = 10;
        }
        levels instance = levels.getInstance();
        instance.setHappiness(changer);
        instance.setGrades(gradeschanger);
        dispose();
    }//GEN-LAST:event_formWindowOpened

    /**
     * 
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lecture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lecture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lecture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lecture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lecture().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
